### PR TITLE
Added icons to each snippet

### PR DESCRIPTION
**Pull request by madskristensen**
Few changes
1. Added an icon for each snippets
   - Each icon works for both Light and Dark theme
2. Update the titles of each snippet
   - Removed _Bootstrap 3.x_ and change casing
3. Updated .csproj file so the VSIX project can be opened in VS2015 as well VS2013

### CODE REVIEW

**Comment by elebetsamer** [comment]
Can you still debug (F5 or Ctrl-F5) this build? I don't seem to be able to.

**Comment by madskristensen** [comment]
No, I couldn't do that before this build either.

**Comment by elebetsamer** [comment]
Hmm, strange, I used to be able to. I wonder why? I just tried to create a fresh vsix project and it lets me debug without a problem. I guess I'll have to investigate deeper. Thanks for the confirmation though.

**Comment by elebetsamer** [comment]
I still don't see the icons in my VS 2015 Enterprise. Is this feature in an update coming down the road?

image

**Comment by madskristensen** [comment]
It’s not released until mid to late November with the ASP.NET 5 RC release.

**Pull request merged**
